### ISSUE TITLE
Actualizar datos por regiones

### ISSUE THREAD

**Issue by pescap** [YachayData/COVID-19#28]
El github action ejecutando actualizarRegiones.py tiene error en extraerDatosRegiones, ya que se cambiaron las columnas en 
https://www.minsal.cl/nuevo-coronavirus-2019-ncov/casos-confirmados-en-chile-covid-19/

- Agregar las nuevas columnas en el github action nuevo y volver a hacerlo funcionar.

- Consolidar la información faltante a partir de otro repositorio (por ejemplo MinCiencias).

**Comment by felipe-mesa** [comment]
`import pandas as pd
url = 'https://www.minsal.cl/nuevo-coronavirus-2019-ncov/casos-confirmados-en-chile-covid-19/'
tables = pd.read_html(url)
df = tables[0]
df = df.drop([0,18,19])
header = df.iloc[0]
df = df[1:]
df.columns = header`

**Comment by pescap** [comment]
¿Lo probaste? Si te funciona, envia Pull Request.
Luego, vamos a tener que actualizar manualmente la tabla con todos los datos faltantes de los dos meses. ¿Alguna recomendación?
Info: https://github.com/jorgeperezrojas/covid19-data
